# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: frontyard
email: frontyardprojects@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Not-Only-Artist Run Initiative. A pro-active, flexible space for practical skills-sharing, community cultural engagement and critical research, with arts at its heart. Our aim is to challenge, facilitate and nurture collaborations between people with a passion for culture and to build a more resilient and sustainable independent arts community for the future.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frontyardprojects.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true

collections:
  supporters:
    output: false
  residents:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

prose:
  media: images
  siteurl: 'http://www.frontyardprojects.org'
  ignore: ['CNAME', '_config.yml', 'css', 'js', '_posts','_layouts','_includes','_sass', '.gitignore']
  metadata:
    _residents:
      - name: name
        field:
          element: text
          label: 'Residents name'
      - name: location
        field:
          element: select
          label: location
          options:
            - name: 'Getaroom A'
              value: 'Getaroom A'
            - name: 'Getaroom B'
              value: 'Getaroom B'
            - name: 'Library'
              value: 'The Library'
            - name: 'Out the back'
              value: 'Out the back'
      - name: dates
        field:
          element: text
          label: dates of residency
    _supporters:
      - name: month
        field:
          element: 'text'
          label: month covered (eg. January not Jan)
